export const productsData = [{
        title: "Bed",
        price: 120,
        imgUrl: "./img/Bed.jpg",
        id: 1,
    },
    {
        title: "Desk",
        price: 32,
        imgUrl: "./img/Desk.jpg",
        id: 2,
    },
    {
        title: "Lamp",
        price: 12,
        imgUrl: "./img/Lamp.jpg",
        id: 3,
    },
    {
        title: "Sofa",
        price: 160,
        imgUrl: "./img/Sofa.jpg",
        id: 4,
    },
    {
        title: "Bed",
        price: 134,
        imgUrl: "./img/Smart Bed.jpg",
        id: 5,
    },
    {
        title: "Bed",
        price: 120,
        imgUrl: "./img/Master Bed.png",
        id: 6,
    },
    {
        title: "Lamp",
        price: 20,
        imgUrl: "./img/Light.jpg",
        id: 7,
    },
    {
        title: "Lamp",
        price: 15,
        imgUrl: "./img/Modern Light.jpg",
        id: 8,
    },
    {
        title: "Bed",
        price: 145,
        imgUrl: "./img/Chic Mid Bed.jpg",
        id: 9,
    },
    {
        title: "Desk",
        price: 42,
        imgUrl: "./img/Desk Office.jpg",
        id: 10,
    },
    {
        title: "Television",
        price: 210,
        imgUrl: "./img/Modern Tv.jpg",
        id: 11,
    },
    {
        title: "Television",
        price: 195,
        imgUrl: "./img/Tv.jpg",
        id: 12,
    },
];